### PR TITLE
Update image names and descriptions

### PR DESCRIPTION
**Pull request by apdibbo**
Updating to reflect new images, deprecated images and changes in naming schemes

### CODE REVIEW

**Review by DavidFair — CHANGES_REQUESTED** [review]
Is it possible to append some sort of date tag to the image name, e.g:

`ubuntu-focal-20.04-rel-21-04` for April

This way a user who has instances can easily see, "Oh I was using the 21-02 image on my machine and now were on 21-09, so there may be breakage"

**Comment by apdibbo** [comment]
It is possible but the aim with the images is for them to generally keep the same name so that if people are building systems using the name the always get the latest image. The out dated images get renamed to `warehoused-<imagename>-<date image was archived>` (we used to use archived but that clogged up the top of lists)

**Review by DavidFair — APPROVED** [review]

**Comment by DavidFair** [comment]
@apdibbo Do you want me to wait for the other assignees to check this over?

**Comment by apdibbo** [comment]
That's fine, merge away

**Pull request merged**
