### PR TITLE
Update LB instructions to make it clear you don't need nginx

### PR DESCRIPTION
**Pull request by DavidFair**
Updates the Load Balancer instructions to make it clear that a user does
not need to create an Nginx instance, it's simply a service for someone
to test against

### CODE REVIEW

**Comment by ElliottKasoar** [comment]
`The steps will be similar to bespoke systems too.`
I may be misreading, but should this be "for bespoke systems"?

`set Port 200 (which we’ve randomly selected)`
Are there any ports that should be avoided? If so, might be worth mentioning here?

I don't think I can actually approve this, but looks good to me otherwise.

**Review by ElliottKasoar — CHANGES_REQUESTED** [review]
`The steps will be similar to bespoke systems too.`
I may be misreading, but should this be "for bespoke systems"?

`set Port 200 (which we’ve randomly selected)`
Are there any ports that should be avoided? If so, might be worth mentioning here?

I'm not sure if I can actually approve this, but looks good to me otherwise.

**Comment by DavidFair** [comment]
I've updated those, thanks for pointing them out.
In this case feel free to approve and merge it when you're happy as it's a documentation repository

**Review by ElliottKasoar — APPROVED** [review]

**Comment by ElliottKasoar** [comment]
> In this case feel free to approve and merge it when you're happy as it's a documentation repository

Ah, the approving reviewer needs write access, which I don't have unfortunately.

**Review by apdibbo — APPROVED** [review]

**Pull request merged**
